ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy

Licence Connect Core is developed as a Spring Boot (see <<adr1>>) web application providing a REST API.

In general, we integrate each licence holding system implementing an isolated client.
This isolated client shall provide a clear interface, providing a method to fetch all licences provided by the licence holding system as a list of ODRL permissions.

When queried by VIDIS for licences, a LicencesCollector can then query each client for the licences and wrap the results in one ODRL policy that is returned to VIDIS.

=== Integrating a licence holding system

To integrate a new licence holding system, the following steps need to be taken:

1. Create a module for the client in `api/src/main/java/com/fwu/lc_core/licences/clients`
2. Implement a client that calls the licence holding system to retrieve licences. 
You can use the `LCHaltClient` or `ArixClient` as guides.
3. Implement a parser that converts the contents returned by the licence holding system into a `List<ODRLPolicy.Permission>.`. 
You can use the `LCHaltParser` or `ArixParser` as guides.
4. In the client, implement a method `public Mono<List<ODRLPolicy.Permission>> getPermissions()` that retrieves the licences from the licence holding system and uses the newly implemented parser to parse them. 
The method can use any or all of the four parameters `bundesland`, `standortnummer`, `schulnummer` and `userId`.
5. Add an enum case for the new licence holding system to the `LicenceHolder` enum, naming it after the licence holding system being integrated.
6. In the `LicenceCollector.permissionsFor(Licencee licencee, LicenceHolder licenceHolder)` method, add the new client and return the licences. 
You can use the usage for LC-Halt or Arix as guides.

Now, once you enable the new licence holding system for a `clientName` via the `/admin/client-licence-holder-mapping` endpoint, you will be able to retrieve licences from the newly integrated system for that `clientName`.

=== Possible Extensions

* With a growing number of licence holders we may want to implement an abstract class containing the implementation of the `getPermissions` method.
We can then require the implementation of the `assertParametersAreValid` and parsing methods.
* In the future, we may implement a generic licence holder client that can be configured to connect to 1:n licence holder adapters via http.
That way it would be possible to integrate new licence holding systems by deploying a separate adapter and configuring the generic client to talk to it.
That would enable integrations without changes to the code of licence connect core itself.

=== Current Deviations

The current connections to the Bilo v2 API deviates from the solution strategy described above.
To integrate them, Licence Connect Core provides dedicated endpoints.
This is due to different requirements of BiLo when retrieving the licences as a licence consumer.
