stages:
#  - build
#  - create_test_image
  - test
  - docker

variables:
  _IMAGE_PATH: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/api

  MAVEN_IMAGE: maven:3-amazoncorretto-21
  TEST_IMAGE: $_IMAGE_PATH/corretto-with-python:testing

  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--settings mvn_ci_settings.xml --batch-mode --errors --fail-at-end"
  MAVEN_CLI_TEST_OPTS: "-Dspring.profiles.active=auto-start-mocks"

  DEVELOP_IMAGE_TAG: $_IMAGE_PATH:develop
  RELEASE_IMAGE_TAG: $_IMAGE_PATH:$CI_COMMIT_TAG

  NETZHAUT_DOCKER_HOST: 172.17.0.1

  #DOCKER_HOST: tcp://docker:2375
  #DOCKER_TLS_CERTDIR: ""
  #COMPOSE_PROJECT_NAME: ${CI_JOB_ID}  # Unique name for each job

cache:
  paths:
    - ".m2/repository"

default:
  tags:
    - docker

# build:
#  stage: build
#  image: $MAVEN_IMAGE
#  script:
#    - mvn $MAVEN_CLI_OPTS compile $MAVEN_OPTS
#  artifacts:
#    paths:
#      - target/
#    expire_in: 30 min

#create_test_image_job:
#  image: docker:27
#  stage: create_test_image
#  script:
#    - docker build . -f src/test/resources/Dockerfile -t $TEST_IMAGE
#    - echo $CI_JOB_TOKEN | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
#    - docker push $TEST_IMAGE

#test_job:
#  image: $TEST_IMAGE
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test $MAVEN_OPTS $MAVEN_CLI_TEST_OPTS

test_job:
  image: docker:latest
  stage: test
  script:
    - apk add --no-cache openjdk21-jre maven curl
    - docker info
    - docker context inspect
    - docker compose -f src/mock-licence-servers/docker-compose.yml up --build --wait
    - curl -f http://$NETZHAUT_DOCKER_HOST:1235/healthcheck
    - mvn test
  after_script:
    - docker compose -f src/mock-licence-servers/docker-compose.yml down

docker_job:
  image: $MAVEN_IMAGE
  stage: docker
  only:
    - develop
  script:
    - mvn $MAVEN_CLI_OPTS spring-boot:build-image
      -DskipTests=true
      -Ddocker.registry.username=gitlab-ci-token
      -Ddocker.registry.password=$CI_JOB_TOKEN
      -Ddocker.registry.url=$CI_REGISTRY
      -Dspring-boot.build-image.publish=true
      -Dspring-boot.build-image.imageName=$DEVELOP_IMAGE_TAG
