# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
image: node:20

stages:
  - build

.node_cached:
  tags:
    - docker
  cache:
    paths:
      - node_modules/
    key:
      files:
        - yarn.lock

install_dependencies:
  stage: .pre
  extends:
    - .node_cached
  script:
    - yarn

build_licence_connect:
  image: 27.2.0-rc.1-cli
  stage: build
  extends:
    - .node_cached
  needs:
    - install_dependencies
  script:
    - docker build . -f docker/node/Dockerfile -t licence-connect
  cache:
    policy: pull

test_licence_connect:
  stage: build
  extends:
    - .node_cached
  needs:
    - build_licence_connect
  script:
    - yarn workspace licence-connect test
  cache:
    policy: pull

test_e2e_licence_connect:
  stage: build
  extends:
    - .node_cached
  needs:
    - build_licence_connect
  script:
    - yarn workspace licence-connect test:e2e
  cache:
    policy: pull
