=== ADR 6: Mapping ARIX Response to ODRL

Date: 2025-05-05

==== Status

Accepted

==== Context

Licence servers provide licences in individual formats.
The currently connected licence holding system ARIX responds in the following format:

```xml
<result>
    <r identifier="ARIX_IDENTIFIER_MEDIUM_A">
        <f n="nr">Some Number</f>
        <f n="licence">YYYY-MM-DD</f>
        <f n="titel">Some Title for medium A</f>
	    ... a bunch of other metadata
    </r>
    <r identifier="ARIX_IDENTIFIER_MEDIUM_B">
        <f n="nr">Some Number</f>
        <f n="licence">YYYY-MM-DD</f>
        <f n="titel">...</f>
	    ... a bunch of other metadata
    </r>
    ... usw.
</result>
```

Where the result contains a list of media.
Each medium has an identifier and additional fields (nr, licence, titel etc.) that can be requested via the query.

As LC focuses on the transmission of licences and not additional meta information, we aim for a minimal set of data required for licensing.
In order to provide a generic API, LC will map them to a standard.

For this, the [ODRL standard](https://www.w3.org/TR/odrl-model/) has been selected as documented in ADR-5.

An example for a set policy taken from the ODRL spec looks like this:

```json
{
    "@context": "http://www.w3.org/ns/odrl.jsonld",
    "@type": "Set",
    "uid": "http://example.com/policy:1010",
    "permission": [{
        "target": "http://example.com/asset:9898.movie",
        "action": "use"
    }]
}
```

==== Considered Options

> **Note**
As opposed to other ADRs, this one will not describe different options but will simply describe the mapping used in this case.

===== Mapping ARIX -> ODRL

In the ODRL standard the list of licensed media translates to a [policy](https://www.w3.org/TR/odrl-model/#policy-set). 
We map all licences transmitted by ARIX to a single policy.

Translating the above example to a policy would look like this:

```json
{
 "@context": "http://www.w3.org/ns/odrl.jsonld",
 "@type": "Set",
 "uid": "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6",
 "permission":
	[
	  {
 	    "target": "ARIX_IDENTIFIER_MEDIUM_A",
	    "assigner": "ARIX",
	    "action": "use"
 	  },
 	  {
 	    "target": "ARIX_IDENTIFIER_MEDIUM_B",
	    "assigner": "ARIX",
	    "action": "use"
	  }
	]
}
```

We use `@type` `Set`, because this is the most sensible option and [used like this by schulconnex](https://github.com/Schulconnex/Schulconnex/blob/lizenzen/src/openapi/paths-policies-info.yaml).

The `uid` is a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) that is dynamically generated for each request and represented as an IRI.

> Alternatives for a UUID were discussed. 
E.g. constructing a semantic id based on the request parameters (may leak information) or persisting/logging the policies previously handed out (too much effort without an explicit requierement).

Each medium from the ARIX response is mapped to one permission.

The `target` is the medium identifier.

The assigner is `ARIX`.
This attribute can be used in the future so that consumers of LC know how to use this permission.

The `action` is `use` for now, as there is no requirement for a more fine-grained description for now.

==== Decision

We do the mapping as proposed.

==== Consequences

- the current response from ARIX needs to be mapped to ODRL
- the ODRL standard may not prove to be the perfect format to transmit secret information (e.g. licence codes)
- there may be further decisions necessary for the mapping for licence holding systems that work different from ARIX
- Appropriately processing the licence information handed out by LC is a responsibility for the consumer