=== ADR 7: Framework for LC Halt

Date: 2025-05-23

==== Status

Draft

==== Context

As a reference for a licence holding system, we will develop 'LC Halt' as a small prototype.
Potentially, it may get extended to support more types of licences.
It may be of use as a reference to other licence holding systems how the interface to licence connect core can be designed.

LC Halt should provide an API to manage licences for states, schools or specific users.
On request, it will hand out the respective licences.
It should provide a SwaggerUI and OpenAPI spec and persist the configured licences also after restarting the application.
The authentication at the API can be done with API keys.

==== Considered Options

|===
||Spring Boot|NestJS|Flask|FastAPI

|Experience in the team / Fit to existing code base
|Very good fit
|Has previously been discontinued, see <<adr01>>
|Has already been used for the mock licence services
|Similar to flask

|Easy setup
|Yes
|Yes
|Yes
|Yes

|Automatic OpenAPI spec generation
|Yes
|Yes
|Yes, with plugin
|Yes

|Easy integration of common databases
|Yes
|Yes
|Yes
|Yes

|Verbosity
|A lot of boilerplate required
|Some boilerplate required
|Only a few files needed
|Only a few files needed
|===

==== Decision


==== Consequences

