networks:
  lc_net:
    driver: bridge

services:
  lc-halt:
    networks:
      - lc_net
    image: ${LC_HALT_IMAGE}
    env_file:
      - ../.env
    profiles:
      - complete-setup
    expose:
      - "8000"

  mongodb:
    image: mongo:8.0
    restart: always
    env_file:
      - ../.env
    expose:
      - "27017"
