services:
  lc-halt:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ../.env
    profiles:
      - complete-setup
    ports:
      - "8000:80"

  mongodb:
    image: mongo:8.0
    restart: always
    env_file:
      - ../.env
    ports:
      - "27017:27017"
