[project]
name = "lc-halt"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]==0.115.12",
    "motor==3.7.1",
    "pytest==8.3.5",
]
