@startuml
!include https://raw.githubusercontent.com/johthor/DomainStory-PlantUML/main/domainStory.puml

Person(Schüler)
Person(Lehrer)
Person(Schule)
System(Videoplattform)
 
activity(_, Lehrer, wählt für Unterrichtsstunde, Document: Video, bei, Videoplattform)
activity(_, Lehrer, bestellt, Document: Video, bei, Schule)
activity(_, Schule, bestellt, Document: Video mit Laufzeit, bei, Videoplattform)
activity(_, Videoplattform, übermittelt, Document: Lizenzcode, an, Schule)
activity(_, Schule, übermittelt, Document: Lizenzcode, an, Lehrer)
activity(_, Lehrer, übermittelt, Document: Lizenzcode, an, Schüler)
activity(_, Schüler, loggt sich ein bei, Videoplattform)
activity(_, Schüler, trägt, Document: Lizenzcode, ein bei, Videoplattform)
activity(_, Schüler, ruft, Document: Video, ab bei, Videoplattform)
@enduml