spring.application.name=lc_core
vidis.api-key=secret-api-key
server.max-http-request-header-size=32KB
ucs.api.v1.authentication.endpoint="https://fwu.myschool.bildungslogin.de/ucsschool/apis/auth/token"
ucs.api.v1.authentication.admin_username=${UCS_ADMIN_USERNAME}
ucs.api.v1.authentication.admin_password=${UCS_ADMIN_PASSWORD}