@startuml C4_Elements
!include <C4/C4_Component>
!include <office/Servers/application_server>
SHOW_PERSON_OUTLINE()

AddRelTag("dashed", $lineStyle = DashedLine())

System_Ext(vidis, "Vidis", "")
System_Boundary(c1, "LC core"){

    Boundary(bilo_system, "Bilo Domain"){
        Component(lc_bilo_v1, "Bilo V1 Lizenzen Controller", "")
        Component(lc_bilo_v2, "Bilo V2 Lizenzen Controller", "")
    }
    Boundary(generic_licence_system, "Generic Licence Domain"){
        Component(lc_licenses, "Lizenzen Controller", "")
        Component(lc_parser, "Lizenz Parser", "")
        Component(lc_collector, "Lizenz Sammler", "")
        Boundary(lc_config_system, "Konfiguration [?]\n"){
            Component(lc_config, "Konfiguration", "Konfiguration der einzelnen lizenzhaltenden Systeme")
            Component(lc_rights, "Berechtigungen", "")
            Component(lc_config_app, "Konfiguration UI", $sprite="application_server")
            ContainerDb(lc_config_db, "Konfiguration Datenbank", "")
        }
    }

    Component(lc_auth, "Authorisierer", "")
    
    Rel_U(lc_licenses, lc_auth, "nutzt", "",$tags="dashed")
    Rel_D(lc_bilo_v1, lc_auth, "nutzt", "",$tags="dashed")
    Rel_D(lc_bilo_v2, lc_auth, "nutzt", "",$tags="dashed")
    Rel_D(lc_licenses, lc_parser, "nutzt", "")
    Rel_D(lc_licenses, lc_collector, "nutzt", "")
    Rel_D(lc_collector, lc_config, "nutzt [?]", "")
    Rel_D(lc_parser, lc_config, "nutzt [?]", "")
}
System_Ext(lh1, "Lizenzhalter [1..]", "")
System_Ext(bilo_v1, "Bilo_v1", "")
System_Ext(bilo_v2, "Bilo_v2", "")

Lay_R(vidis, c1)
Lay_R(lc_config, lc_rights)
Lay_R(lc_parser, lc_collector)
Lay_D(lc_config, lc_config_db)
Lay_R(lc_config_db, lc_config_app)
Lay_D(lc_bilo_v1, lc_bilo_v2)
Lay_D(bilo_v1, bilo_v2)


Rel_R(vidis, lc_licenses, "Lizenzen anfragen (Generisch)", "GET Enpunkt")
Rel_R(vidis, lc_bilo_v1, "Lizenzen anfragen (Bilo)", "GET Endpunkt")
Rel_R(vidis, lc_bilo_v2, "Lizenzen anfragen (Bilo)", "GET Endpunkt")
Rel_R(lc_collector, lh1, "Lizenzen anfragen","")
Rel_R(lc_bilo_v1, bilo_v1, "Lizenzen anfragen","")
Rel_R(lc_bilo_v2, bilo_v2, "Lizenzen anfragen","")

@enduml