@startuml C4_Elements
!include <C4/C4_Component>
!include <office/Servers/application_server>
SHOW_PERSON_OUTLINE()

AddRelTag("dashed", $lineStyle = DashedLine())

System_Ext(vidis, "Vidis", "")
System_Boundary(c1, "LC core"){
    Boundary(bilo_system, "Bilo Domain"){
        Component(lc_bilo_v1, "Bilo V1 Lizenzen Controller", "")
        Component(lc_bilo_v2, "Bilo V2 Lizenzen Controller", "")
    }
    Boundary(generic_licence_system, "Generic Licence Domain"){
        Component(lc_licenses, "Lizenzen Controller", "")
        Component(lc_parser, "Lizenz Parser", "")
        Component(lc_collector, "Lizenz Sammler", "")
    }

   Boundary(lc_shared_system, "Shared Domain"){
        Component(lc_auth, "Authorisierer", "")
        Component("lc_client_licence_holder_filter", "Zugriffsfilter", "")
        Component("lc_client_licence_holder_filter_controller", "Zugriffsfilterkonfiguration Controller", "")
        ContainerDb(lc_config_db, "Zugriffsfilterdatenbank", "")
        Rel_D(lc_client_licence_holder_filter_controller, lc_client_licence_holder_filter, "erlaubt Anpassung", "")
        Rel_D(lc_client_licence_holder_filter, lc_config_db, "nutzt", "")
    }


    Rel_U(lc_licenses, lc_auth, "nutzt", "",$tags="dashed")
    Rel_D(lc_bilo_v1, lc_auth, "nutzt", "",$tags="dashed")
    Rel_D(lc_bilo_v2, lc_auth, "nutzt", "",$tags="dashed")
    Rel_D(lc_licenses, lc_parser, "nutzt", "")
    Rel_D(lc_licenses, lc_collector, "nutzt", "")
}
System_Ext(lh1, "Lizenzhalter [1..]", "")
System_Ext(bilo_v1, "Bilo_v1", "")
System_Ext(bilo_v2, "Bilo_v2", "")

Lay_R(vidis, c1)
Lay_R(lc_parser, lc_collector)
Lay_D(lc_bilo_v1, lc_bilo_v2)
Lay_D(bilo_v1, bilo_v2)


Rel_R(vidis, lc_licenses, "Lizenzen anfragen (Generisch)", "GET Enpunkt")
Rel_R(vidis, lc_bilo_v1, "Lizenzen anfragen (Bilo)", "GET Endpunkt")
Rel_R(vidis, lc_bilo_v2, "Lizenzen anfragen (Bilo)", "GET Endpunkt")
'If the third argument of the relation is an empty string, some'
'PlantUML/GraphViz version combinations throw an IllegalArgumentException'
Rel_U(lc_licenses, lc_client_licence_holder_filter,  " ", "")
Rel_R(lc_bilo_v1, lc_client_licence_holder_filter,  " ", "")
Rel_R(lc_bilo_v2, lc_client_licence_holder_filter,  " ", "")
Rel_R(lc_collector, lh1, "Lizenzen anfragen","")
Rel_R(lc_bilo_v1, bilo_v1, "Lizenzen anfragen","")
Rel_R(lc_bilo_v2, bilo_v2, "Lizenzen anfragen","")

@enduml
