version: '3.8'

services:
  mock-arix-server-accepting:
    build:
      context: arix-accepting
    ports:
      - "127.0.0.1:1234:1234"
  mock-arix-server-rejecting:
    build:
      context: arix-rejecting
    ports:
      - "127.0.0.1:1235:1235"
  mock-bilo-v2-server:
    build:
      context: bilo-v2
    ports:
      - "127.0.0.1:1236:1236"
    volumes:
      - ../test/resources/application.properties:/app/application.properties:ro
  mock-bilo-v1-server:
    build:
      context: bilo-v1
    ports:
      - "127.0.0.1:1237:1237"
    volumes:
      - ../test/resources/application.properties:/app/application.properties:ro