services:
  nginx:
    image: nginx:latest
    container_name: lc-nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - licence-connect
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://licence-connect:8080/v1/healthcheck" ]
      interval: 1s
      timeout: 5s
      retries: 100

  licence-connect:
    image: ${LC_IMAGE}
    container_name: licence-connect
    env_file: ".env"
    volumes:
      - ${DB_FILE_PATH:-./db}:/workspace/data
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/workspace/data/database.h2;DB_CLOSE_ON_EXIT=FALSE

  loki:
    image: grafana/loki:latest
    container_name: lc-loki
    ports:
      - "3100:3100"

  grafana:
    profiles: [debug]
    image: grafana/grafana:latest
    container_name: lc-debug-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

