services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always
    depends_on:
      - licence-connect

  licence-connect:
    image: licence-connect:latest
    container_name: licence-connect
    env_file: ".env"
    ports:
      - 3000:3000
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_LABEL_ENABLE: true
      REPO_USER: ${REPO_USER}
      REPO_PASS: ${REPO_PASS}
