services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - licence-connect

  licence-connect:
    image: gitcr.fwu.de/licenceconnect/api/licence-connect:develop
    container_name: licence-connect
    pull_policy: always
    env_file: ".env"
    ports:
      - "8080:8080"
