services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - licence-connect
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://licence-connect:8080/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 10

  licence-connect:
    image: ${LC_IMAGE}
    container_name: licence-connect
    env_file: ".env"
    ports:
      - "8080:8080"
