services:
  nginx:
    image: nginx:latest
    container_name: lc-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - licence-connect
      - lc-halt
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://licence-connect:8080/v1/healthcheck && curl -f http://lc-halt:80/health"]
      interval: 5s
      timeout: 5s
      retries: 100

  licence-connect:
    image: gitcr.fwu.de/licenceconnect/api:latest
    container_name: licence-connect
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - ${DB_FILE_PATH:-./db}:/workspace/data
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/workspace/data/database.h2;DB_CLOSE_ON_EXIT=FALSE

  lc-halt:
    image: gitcr.fwu.de/licenceconnect/api/lc-halt:latest
    container_name: lc-halt
    env_file: ../.env

  mongodb:
    image: mongo:8.0
    restart: always
    expose:
      - "27017"
    env_file: ../.env

  loki:
    profiles: [debug]
    image: grafana/loki:latest
    container_name: lc-loki
    expose:
      - "3100"

  grafana:
    profiles: [debug]
    image: grafana/grafana:latest
    container_name: lc-debug-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      # With this volume, we can persist the data in local development even if the container is removed.
      # This is useful because it removes the need to re-add the Loki datasource every time you start the container.
      - ./grafana_data:/var/lib/grafana
