ifndef::imagesdir[:imagesdir: ../images]

[[section-building-block-view]]

== Building Block View

=== Level 1: Whitebox Overall System

[plantuml]
----
@startuml Building_Block_Level_1
!include <C4/C4_Component>
!include <office/Servers/application_server>
SHOW_PERSON_OUTLINE()

Person(admin, "Administrator")

AddRelTag("dashed", $lineStyle = DashedLine())

System_Ext(vidis, "Vidis", "")
System_Ext(lchalt, "LC Halt", "")
System_Ext(arix, "Arix", "")
System_Ext(bilo_v1, "Bilo_v1", "")
System_Ext(bilo_v2, "Bilo_v2", "")
System_Ext(vidis, "Vidis", "")

System_Boundary(c1, "Licence Connect Core"){
    Component(lc_client_mapping, Client Licence Holder Mapper)
    Component(lc_licences, Licences)
    Component(lc_bilo, BiLo)
    Component(lc_config, Config)

    ComponentDb(db, "Database")
}

Rel(admin, lc_client_mapping, "Freigeschaltete Lizenzhalter für Clients konfigurieren")
Rel(vidis, lc_licences, "Lizenzen anfragen (für clientName)")
Rel(vidis, lc_bilo, "BiLo Lizenzen anfragen")
Rel_R(lc_licences, lc_client_mapping, "Freigeschaltete Lizenzhalter für client abrufen")
Rel(lc_licences, lchalt, "Lizenzen anfragen")
Rel(lc_licences, arix, "Lizenzen anfragen")
Rel_R(lc_client_mapping, db, "Zugriffsfilter konfigurieren")

Rel(lc_bilo, bilo_v1, "")
Rel(lc_bilo, bilo_v2, "")

@enduml
----

[cols="e,2a" options="header"]
|===
|Building Blocks |Notes

|Licences|
The Licences module is the main module providing the API for VIDIS and fetching licences from different licence holding systems.

|Client Licence Holder Mapping|
The Client Licence Holder Mapping module enables administrators to enable/disable different licence sources for different licence consumers.
The Licences module can then retrieve licences only from licence sources that are enabled for the requesting consumer.

|Config|
The Config module configures relevant parts of Licence Connect Core, e.g. authentication or logging.

|BiLo|
The BiLo module is responsible for enabling VIDIS to fetch BiLo licences.
It is separated due to different requirements of the respective consumers.

|===

=== Level 2

==== Licences

[plantuml]
----
@startuml

[VIDIS] as vidis #white
[LC Halt] as lchalt #white
[Arix] as arix #white

[client licence holder mapper] as client_mapper

package Licences {
    [Arix Client] as arix_client
    [LC Halt Client] as lchalt_client
    [LicencesController] as lcontroller
    [LicencesCollector] as lcollector
}

vidis --> lcontroller: Fragt nach Lizenzen für \n(Bundesland, Schulnummer, UserId, ClientName)
lcontroller --> lcollector: Fragt nach Lizenzen für \n(Bundesland, Schulnummer, UserId, ClientName)
lcollector --> client_mapper: Fragt nach freigegebenen \n Lizenzhaltern für ClientName
lcollector --> arix_client: Ruft Lizenzen ab für \n(Bundesland, Schulnummer, UserId)
lcollector --> lchalt_client: Ruft Lizenzen ab für \n(Bundesland, Schulnummer, UserId)
arix_client --> arix
lchalt_client --> lchalt

@enduml
----

[[vidis-interface]]
===== Interface to VIDIS

VIDIS fetches licences, generally using the endpoint `/licences/request` provided by this module.
The following list contains the parameters and how VIDIS obtains them:

|===
|Parameter|Notes

|`clientName`
|Each system connected to the VIDIS-SSO has a dedicated client.
The id of this client will also be the clientId VIDIS provides to LC Core for this query.

|`userId`
|The `userId` is usually the id of the user in the IDP of the federal state. 
E.g. if a user has the userId "abc" in the bavarian school portal, VIDIS will request licences for this userId, *not* the id assigned by VIDIS.

|`bundesland`
|The federal state where the user account originated from.

|`standortnummer`
|Is supposed to be the "Landkreis" where the school is located.
This value is currently not provided since it is not yet clarified how to resolve this.

|`schulnummer`
|The id of the school of the user.
Provided to VIDIS by the IDP of the federal state.
|=== 

[[arix-interface]]
===== ARIX Interface

ARIX is available at http://arix.datenbank-bildungsmedien.net/

Each request must specify a context in the path, containing [land]/[standortnummer]/[schulnummer]/[user-id]. 
At least land must be present, in the example above "stk" is the land and "str" is the standortnummer.

.Example Request to ARIX
```
curl -X POST http://arix.datenbank-bildungsmedien.net/stk/str -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "xmlstatement=<search fields='nr,titel,prodjahr' limit='3'></search>"
```

As a mock for development purposes there are `mock-licence-servers/arix-accepting` and `mock-licence-servers/arix-rejecting` in this repository.

====== Authentication

ARIX only responds to whitelisted IPs.
For local development, a VPN with a whitelisted static IP is necessary to successfully query ARIX for licences.

==== Client Licence Holder Mapper

[plantuml]
----
@startuml

:Admin: as admin

[LicencesCollector] as lcollector
database Database as db

package "client licence holder mapper" {
    [ClientLicenceHolderFilterController] as controller
    [ClientLicenceHolderFilterService] as service
    [ClientLicenceHolderMappingRepository] as repository
}

admin --> controller: Client Mappings verwalten
controller --> service: Client Mappings verwalten
lcollector --> service: Client Mappings abrufen
service --> repository: Client Mappings verwalten
service --> repository: Client Mappings abrufen
repository --> db: Client Mappings persistieren/abrufen

@enduml
----

The client licence holder mapping allows the administrator to control which licence holders are requested for which client requests.
Each mapping maps one client name to 0:n licence holders.
Each request to lc core requesting licences must provide a client name.
