ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Context and Scope

=== Context Diagram

[plantuml]
----
@startuml Context_and_Scope
!include <C4/C4_Container>
SHOW_PERSON_OUTLINE()

Person_Ext(student, "Student", "")
Person_Ext(teacher, "Teacher", "")
Person(admin, "Administrator", "")

System_Ext(licence_consumer, "Licence Consumer", "e.g. Educational Offer, Publisher, Bilo")
System_Ext(vidis, "VIDIS", "")

System_Ext(lcmedia, "LC-Media", "A demo licence consuming system")

System(lc, "Licence Connect Core", "")

System_Ext(lchalt, "LC Halt", "")
System_Ext(arix, "Arix", "")
System_Ext(bilo_v1, "Bilo_v1", "")
System_Ext(bilo_v2, "Bilo_v2", "")

Rel(student, licence_consumer, "Use licenced media", "")
Rel(teacher, licence_consumer, "Use licenced media", "")
Rel(lcmedia, vidis, "Retrieve relevant licences", "")
Rel_R(licence_consumer, vidis, "Retrieve relevant licences", "")
Rel(vidis, lc, "Retrieve relevant licences", "")
Rel(lc, lchalt, "Retrieve relevant licences","")
Rel(lc, arix, "Retrieve relevant licences","")
Rel(lc, bilo_v1, "Retrieve relevant licences","")
Rel(lc, bilo_v2, "Retrieve relevant licences","")

Rel(admin, lc, "Enable licence holder for specific consumers")

@enduml
----

[cols="e,2a" options="header"]
|===
|External System |Notes

|VIDIS|
SSO Provider for educational purposes.
https://www.vidis.schule/

Due to the sign in via VIDIS, licence holders only have pseudonyms of users with an extra ID assigned by VIDIS.
In order to assign actual licences to users, the request to LC Core goes through VIDIS.
That way, VIDIS and LC Core can potentially use data that is not available to the licence holder, e.g. the user id in the federal state idp of the user.

See <<vidis-interface>> for more details on how VIDIS communicates with LC Core.

|LC-Halt|
LC-Halt is a demo licence holding system intended to demonstrate licence management.
It is reachable under https://halt.licenceconnect.schule

|LC-Media|
LC-Media is a demo licence consuming system intended to demonstrate licence management.
It is reachable under https://media.licenceconnect.schule

|Arix|
ARIX (Antares Repository Interface/XML) is licence holding system developed and run by the Antares Project: https://www.antares.net

See <<arix-interface>> for more details on ARIX.
|===
