from dataclasses import dataclass
from typing import Optional

STANDARD_FIELD_NAMES = ["licence"]

@dataclass
class ArixLicence:
    id: str
    licence: str

    nr: Optional[str] = "..."
    titel: Optional[str] = "..."
    typ: Optional[str] = "..."
    utitel: Optional[str] = "..."
    sertitel: Optional[str] = "..."
    serutitel: Optional[str] = "..."
    adressat: Optional[str] = "..."
    attribute: Optional[str] = "..."
    laenge: Optional[str] = "..."
    produ: Optional[str] = "..."
    prodjahr: Optional[str] = "..."
    prodland: Optional[str] = "..."
    empfende: Optional[str] = "..."
    vorfbis: Optional[str] = "..."
    vorfrecht: Optional[str] = "..."
    fsk: Optional[str] = "..."
    rechte: Optional[str] = "..."
    begleit: Optional[str] = "..."
    preis: Optional[str] = "..."
    datum: Optional[str] = "..."
    schlag: Optional[str] = "..."
    bemerk: Optional[str] = "..."
    text: Optional[str] = "..."
    geb: Optional[str] = "..."
    sprache: Optional[str] = "..."
    topographie: Optional[str] = "..."
    personen: Optional[str] = "..."
    darsteller: Optional[str] = "..."
    lernziele: Optional[str] = "..."
    vork: Optional[str] = "..."
    praedikate: Optional[str] = "..."
    beigaben: Optional[str] = "..."
    verfanf: Optional[str] = "..."
    verfende: Optional[str] = "..."
    oeffvrecht: Optional[str] = "..."
    fremdvertrieb: Optional[str] = "..."
    regie: Optional[str] = "..."
    lieferant: Optional[str] = "..."
    bildliste: Optional[str] = "..."
    orgtitel: Optional[str] = "..."
    sorttitel: Optional[str] = "..."
    sortutitel: Optional[str] = "..."
    sortsertitel: Optional[str] = "..."
    paratitel: Optional[str] = "..."
    langtext: Optional[str] = "..."
    techtext: Optional[str] = "..."
    drehbuch: Optional[str] = "..."
    kamera: Optional[str] = "..."
    schnitt: Optional[str] = "..."
    ton: Optional[str] = "..."
    eignung: Optional[str] = "..."
    musik: Optional[str] = "..."
    urheber: Optional[str] = "..."
    auftraggeber: Optional[str] = "..."
    herausgeber: Optional[str] = "..."
    litvorlage: Optional[str] = "..."
    einzeltitel: Optional[str] = "..."
    sammelmedien: Optional[str] = "..."
    sprachfassungen: Optional[str] = "..."
    kontextmedien: Optional[str] = "..."
    url: Optional[str] = "..."
    quelle: Optional[str] = "..."
    kuerzel: Optional[str] = "..."
    techdat: Optional[str] = "..."
    autor: Optional[str] = "..."
    paranr2: Optional[str] = "..."
    paranr: Optional[str] = "..."
    didanmerk: Optional[str] = "..."

