ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introduction and Goals

Licence Connect enables schools, school boards and federal German states to manage educational ressources by buying them, assigning them and making them available to users at schools.

The MVP will link the licence management of Mecklenburg-Vorpommern with VIDIS and BiLo.

=== Requirements Overview

LC provides an endpoint to retrieve licence data for a VIDIS user. 
This endpoint will be used by VIDIS.

==== Detailed Requirements

* LicenceConnect provides the ability to add or remove licences of a specific user.
Licences are not assigned to a specific educational offer.
* LicenceConnect does not depend on external systems. 
UCS is not connected right now. 
* On request all available licences for a user are returned.
** Consequence: LicenceConnect will not be able to decide whether a specific user has a licence for a client or not.
** Consequence: LicenceConnect is not able to count the used licences for a specific educational offer.
** Consequence: Defining a "release" endpoint for indicating the the release of a licence is not useful as long as we don't know that licences are used.

=== Quality Goals

* User data and licences may only be handed out securely and only to authorized systems

=== Stakeholders
