ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts

=== Configuration

The configuration of the LicenceConnect system is currently done by using Environment Variables.
These Environment Variables can be set via the .env file next to the Docker Compose file.

Exemplary .env vile

``` .env
include::../../docker/.env.example[]
```

LOG_LEVEL:: 
The Logging level that should be used, it should be one of the following levels:
- _trace_
- _debug_
- _info_
- _warn_
- _error_
- _fatal_

LOG_PATH::
The path where the log file should be placed

LOG_FILE::
The filename used for logging

LICENCE_MANAGER_API_KEY::
The API key that should be used for authentication on the LicenceManagement endpoint

VIDIS_API_KEY::
The API key that should be used for authentication on the vidis endpoint

UCS_API_KEY::
The API key that should be used for authentication on the ucs endpoint

UCS_URL::
The url that is used for fetching the ucs licence object

UCS_TECHNICAL_USER_NAME::
The username for a technical user. This user is used to get a Authentication-Token for the UCS Licence Provider system.

UCS_TECHNICAL_USER_PASSWORD::
The password for a technical user. This user is used to get a Authentication-Token for the UCS Licence Provider system.

==== Current Limitations

* Currently it is not possible to configure more than one UCS Licence Provider.