ifndef::imagesdir[:imagesdir: ../images]

[[section-introduction-and-goals]]
== Introduction and Goals

Licence Connect Core is a "licence broker". 
It is connected to several licence holding systems and can return all relevant licences for a user.

=== Requirements Overview

Licence Connect Core is supposed to:

* retrieve licence information from different sources (aka licence holding systems)
* unify the retrieved licence information in a generic format (ODRL, see <<adr5>>)
* enable VIDIS to retrieve licence information for specific users and clients (aka licence consumers)
* enable administrators to enable or disable sources for specific clients


=== Domain Stories

See <<section-domain-storytelling>> for more infos on the method.

==== Licence Management without Licence Connect and VIDIS

[plantuml]
----
@startuml licences domain story
!$Story_Layout = "portrait"
!include <DomainStory/domainStory>

Person(Schüler)
Person(Lehrer)
Person(Schule)
System(Videoplattform)
 
activity(_, Lehrer, wählt für Unterrichtsstunde, Document: Video, bei, Videoplattform)
activity(_, Lehrer, bestellt, Document: Video, bei, Schule)
activity(_, Schule, bestellt, Document: Video mit Laufzeit, bei, Videoplattform)
activity(_, Videoplattform, übermittelt, Document: Lizenzcode, an, Schule)
activity(_, Schule, übermittelt, Document: Lizenzcode, an, Lehrer)
activity(_, Lehrer, übermittelt, Document: Lizenzcode, an, Schüler)
activity(_, Schüler, loggt sich ein bei, Videoplattform)
activity(_, Schüler, trägt, Document: Lizenzcode, ein bei, Videoplattform)
activity(_, Schüler, ruft, Document: Video, ab bei, Videoplattform)
@enduml
----

* the licence code in this case is an actual secret, activating a licence when entered in the video platform (similar to a licence code contained in the dvd package of a computer game)

==== Licence Management with VIDIS, Licence Connect Core, a Licence Holder and a Media Library

[plantuml]
----
@startuml licencing with lc
!$Story_Layout = "portrait"
!include <DomainStory/domainStory>

Person(Schüler)
System(Mediathek)
System(VIDIS)
System(lccore, LC Kern)
System(länderidp, Länderportal (IDP))
System(Lizenzhalter)
 
activity(v_, Schüler, besucht, Mediathek)
activity(v_, Schüler, triggert Login bei, Mediathek)
activity(>_, Mediathek, leitet für Login weiter an, VIDIS)
activity(v_, VIDIS, leitet für Login weiter an, länderidp)
activity(_, Schüler, loggt sich ein bei, länderidp)
activity(v_, VIDIS, erhält, Document: User Informationen, von, länderidp)
activity(v_, VIDIS, fragt nach Lizenzen für, Document: User Informationen, von, lccore)
activity(_, lccore, fragt nach Lizenzen für, Document: User Informationen, von, Lizenzhalter)
activity(_, Lizenzhalter, antwortet mit, Document: Lizenzen (eigenes Format), an, lccore)
activity(_, lccore, übersetzt Lizenzen in, Document: Lizenzen (ODRL Format))
activity(_, lccore, antwortet mit, Document: Lizenzen (ODRL Format), an, VIDIS)
activity(_, VIDIS, cached, Document: Lizenzen (ODRL Format))
activity(_, VIDIS, antwortet mit, Document: VIDIS Token, an, Mediathek)
activity(_, Mediathek, fragt mit, Document: VIDIS Token, nach Lizenzen bei, VIDIS)
activity(_, VIDIS, antwortet mit, Document: Lizenzen (ODRL Format), aus Cache an, Mediathek)
activity(_, Mediathek, zeigt abhängig von Lizenzen, Document: Medien, an für, Schüler)
@enduml
----